import os
from pathlib import Path

from dotenv import load_dotenv

# ==========================================
# 1. ENVIRONMENT & LANGSMITH SETUP FIRST
# ==========================================
# This MUST run before importing any LangChain/LangGraph tools
load_dotenv()

# Force activate LangSmith tracing globally in your script
os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ["LANGCHAIN_PROJECT"] = "langgraph-aws-chatbot"

# ==========================================
# 2. FRAMEWORK IMPORTS
# ==========================================
from typing import Annotated
from typing_extensions import TypedDict
from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse, RedirectResponse
from pydantic import BaseModel

from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
# Import the specialized Groq module instead of OpenAI
from langchain_groq import ChatGroq

# ==========================================
# 3. LANGGRAPH BOT DEFINITION (GROQ DRIVEN)
# ==========================================

# Define the conversation state structure
class State(TypedDict):
    messages: Annotated[list, add_messages]

# Initialize the Groq model. 
# llama-3.3-70b-versatile or llama-3.1-8b-instant are excellent, fast choices.
# It automatically looks for GROQ_API_KEY inside your environment variables.
llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0.7
)

# Define the brain node that handles user prompts
def chatbot_node(state: State):
    response = llm.invoke(state["messages"])
    return {"messages": [response]}

# Assemble the State Graph 
builder = StateGraph(State)
builder.add_node("chatbot", chatbot_node)
builder.add_edge(START, "chatbot")
builder.add_edge("chatbot", END)

# Compile into an active application
chatbot_app = builder.compile()

_STATIC_DIR = Path(__file__).resolve().parent / "static"

# ==========================================
# 4. PRODUCTION FASTAPI INTERFACE
# ==========================================
api = FastAPI(title="Production Groq + LangGraph Chatbot API")

class HistoryTurn(BaseModel):
    role: str
    content: str


class ChatRequest(BaseModel):
    message: str
    history: list[HistoryTurn] = []

@api.get("/")
def chat_page():
    """Simple browser UI to talk to the bot."""
    path = _STATIC_DIR / "chat.html"
    if not path.is_file():
        raise HTTPException(
            status_code=500,
            detail="Missing static/chat.html — redeploy with the static folder.",
        )
    return FileResponse(path, media_type="text/html; charset=utf-8")


@api.get("/health")
def health():
    """JSON health check for load balancers / Docker."""
    return {"status": "healthy", "service": "groq-langgraph-chatbot"}


@api.get("/chat", include_in_schema=False)
def chat_redirect_to_ui():
    """Old links to GET /chat open the chat page instead of 405."""
    return RedirectResponse(url="/", status_code=307)

@api.post("/chat")
async def chat_endpoint(payload: ChatRequest):
    try:
        messages: list = []
        for turn in payload.history:
            if turn.role in ("user", "assistant") and turn.content.strip():
                messages.append((turn.role, turn.content))
        messages.append(("user", payload.message))

        inputs = {"messages": messages}
        
        # Execute the workflow synchronously
        result = chatbot_app.invoke(inputs)
        
        # Pull out the final response content string generated by Groq
        final_reply = result["messages"][-1].content
        return {"response": final_reply}
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))